# Generated by Django 2.0.4 on 2018-04-06 09:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklanguage',
            name='validation_errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[],
                                                                 verbose_name='Ошибки валидации'),
        ),
    ]
